language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
jobs:
  include:
    - stage: build
      script: ./gradlew compileJava
    - stage: unit-test
      script: ./gradlew test
